apiVersion: v1
kind: ConfigMap
metadata:
  name: llama-stack-config
data:
  config.yaml: |
    version: '2'
    image_name: llamastack/llama-stack:latest
    apis:
      - inference
      - agents
    providers:
      inference:
        - provider_id: rhoai-maas
          provider_type: openai
          config:
            # L'URL correcte de ton modèle
            url: "https://litellm-prod.apps.maas.redhatworkshops.io/v1"
            # On utilise une variable d'environnement dynamique !
            api_key: "${RHOAI_API_KEY}"
    mcp_endpoints:
      - name: jira_mock
        url: "http://jira-mcp-service:8080/sse"